<testsuite name="Mocha Tests" tests="2" failures="3" errors="3" skipped="-1" timestamp="Sat, 04 Aug 2018 19:32:42 GMT" time="0.036">
<testcase classname="" name="Uncaught error outside test suite" time="0"><failure message="listen EADDRINUSE :::8000"><![CDATA[Error: listen EADDRINUSE :::8000
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at Server.setupListenHandle [as _listen2] (net.js:1355:14)
    at listenInCluster (net.js:1396:12)
    at Server.listen (net.js:1480:7)
    at Object.&#x3C;anonymous&#x3E; (main.js:4:29)
    at Module.replacementCompile (node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.&#x3C;anonymous&#x3E; (node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at require (internal/module.js:11:18)
    at Object.&#x3C;anonymous&#x3E; (test.js:3:14)
    at Module.replacementCompile (node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.&#x3C;anonymous&#x3E; (node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at require (internal/module.js:11:18)
    at Array.forEach (&#x3C;anonymous&#x3E;)
    at Module.replacementCompile (node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.&#x3C;anonymous&#x3E; (node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at runMain (/root/.node-spawn-wrap-18956-bd6c6971f498/node:68:10)
    at Function.&#x3C;anonymous&#x3E; (/root/.node-spawn-wrap-18956-bd6c6971f498/node:171:5)
    at Object.&#x3C;anonymous&#x3E; (node_modules/nyc/bin/wrap.js:23:4)
    at /root/.node-spawn-wrap-18956-bd6c6971f498/node:178:8
    at Object.&#x3C;anonymous&#x3E; (/root/.node-spawn-wrap-18956-bd6c6971f498/node:181:3)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3]]></failure></testcase>
<testcase classname="/" name="should return 200" time="0"><failure message="connect ECONNREFUSED 127.0.0.1:3000"><![CDATA[Error: connect ECONNREFUSED 127.0.0.1:3000
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)]]></failure></testcase>
<testcase classname="/" name="should say &#x22;Hello Auto Ops Ltd.&#x22;" time="0"><failure message="connect ECONNREFUSED 127.0.0.1:3000"><![CDATA[Error: connect ECONNREFUSED 127.0.0.1:3000
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)]]></failure></testcase>
</testsuite>
